{% set name = "tofu" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a79cf45add692586d39a1dbaecf96b125a5da78f1199e8b599743079d06d26d3

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tofu-version = scripts.tofuversion:main
    - tofu-custom=scripts.tofucustom:main
    - tofu = scripts.tofu_bash:main

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython => 0.26
    - numpy
    - setuptools
    - openmp  # [unix and not osx]
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - openmp  # [unix and not osx]
    - _openmp_mutex  # [unix and not osx]
    - requests
    - svg.path
    - Polygon3
    - spectrally >=0.0.4

test:
  imports:
    - tofu
    - tofu.geom
  commands:
    # - pytest tofu/tests
    - echo ""
  requires:
    - pytest
  source_files:
    - tofu/tests

about:
  home: https://github.com/ToFuProject/tofu
  license: MIT
  license_file: LICENSE.txt
  summary: Project for an open-source python library for synthetic diagnostics and tomography for Fusion devices.
  description: |
    tofu stands for Tomography for Fusion, it is an IMAS-compatible open-source
    machine-independent python library with non-open source plugins containing all machine-dependent routines.
    It aims at providing the fusion and plasma community with an object-oriented, transparent and documented tool
    for designing tomography diagnostics, computing synthetic signal (direct problem) as well as tomographic
    inversions (inverse problem). It gives access to a full 3D description of the diagnostic geometry, thus reducing
    the impact of geometrical approximations on the direct and, most importantly, on the inverse problem.
    tofu is relevant for all diagnostics integrating, in a finitie field of view or along a set of lines of sight,
    a quantity (scalar or vector) for which the plasma can be considered transparent (e.g.: light in the visible, UV,
    soft and hard X-ray ranges, or electron density for interferometers).

    tofu is command-line oriented, for maximum flexibility and scriptability. The absence of a GUI is compensated by
    built-in one-liners for interactive plots.

    A sphinx-generated documentation and the code itself is hosted on GitHub.
  doc_url: https://tofuproject.github.io/tofu/
  dev_url: https://github.com/ToFuProject/tofu

extra:
  recipe-maintainers:
    - flothesof
    - Didou09
    - lasofivec
