context:
  name: tofu
  version: "1.8.16"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ea0483dc13c2d770ea418bd9e841707ed4b564e8024409fb238b17dc4f2e8031

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - tofu-version = scripts.tofuversion:main
      - tofu-custom=scripts.tofucustom:main
      - tofu = scripts.tofu_bash:main

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython >=0.26
        - numpy
        - llvm-openmp
  host:
    - python
    - pip
    - cython >=0.26
    - numpy
    - setuptools
    - llvm-openmp
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - contourpy
    - requests
    - svg.path
    - Polygon3
    - datastock >=0.0.54
    - bsplines2d >=0.0.27
    - spectrally >=0.0.9

tests:
  - python:
      imports:
        - tofu
        - tofu.geom
  - script:
    - pytest tofu/tests
    files:
      source:
        - tofu/tests
    requirements:
      run:
        - pytest

about:
  homepage: https://github.com/ToFuProject/tofu
  license: MIT
  license_file: LICENSE.txt
  summary: Project for an open-source python library for synthetic diagnostics and tomography for Fusion devices.
  description: |
    tofu stands for Tomography for Fusion, it is an IMAS-compatible open-source
    machine-independent python library with non-open source plugins containing all machine-dependent routines.
    It aims at providing the fusion and plasma community with an object-oriented, transparent and documented tool
    for designing tomography diagnostics, computing synthetic signal (direct problem) as well as tomographic
    inversions (inverse problem). It gives access to a full 3D description of the diagnostic geometry, thus reducing
    the impact of geometrical approximations on the direct and, most importantly, on the inverse problem.
    tofu is relevant for all diagnostics integrating, in a finitie field of view or along a set of lines of sight,
    a quantity (scalar or vector) for which the plasma can be considered transparent (e.g.: light in the visible, UV,
    soft and hard X-ray ranges, or electron density for interferometers).

    tofu is command-line oriented, for maximum flexibility and scriptability. The absence of a GUI is compensated by
    built-in one-liners for interactive plots.

    A sphinx-generated documentation and the code itself is hosted on GitHub.
  documentation: https://tofuproject.github.io/tofu/
  repository: https://github.com/ToFuProject/tofu

extra:
  recipe-maintainers:
    - flothesof
    - Didou09
    - lasofivec
